name: Compilar todos los .tex dinámicamente

on:
  push:
    branches:
      - main
    paths:
      - 'materias/**/*.tex'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar LaTeX
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            latexmk
            texlive-latex-recommended
            texlive-latex-extra
            texlive-fonts-recommended
            texlive-xetex
            texlive-lang-spanish

      - name: Compilar todos los .tex encontrados
        run: |
          find materias -type f -name '*.tex' | while read file; do
            echo "📄 Compilando $file"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$file"
          done

      - name: Subir PDFs
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: '**/*.pdf'
