name: Compilar Apuntes LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'materias/Calculo_D/primerParcial/primerParcial.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Compilar LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: materias/Calculo_D/primerParcial/primerParcial.tex

      - name: Mostrar árbol de archivos generado
        run: |
          echo "Contenido del workspace:"
          pwd
          ls -lhR

      - name: Subir PDF compilado
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: '**/primerParcial.pdf'
