name: Compilar LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'materias/**/*.tex'

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Compilar todos los .tex en materias/
        run: |
          find materias -type f -name '*.tex' | while read file; do
            echo "Compilando $file"
            latexmk -pdf -interaction=nonstopmode -halt-on-error "$file"
          done

      - name: Mostrar árbol de archivos generado
        run: |
          echo "Contenido del workspace:"
          pwd
          ls -lhR

      - name: Subir PDFs compilados
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: '**/*.pdf'
