name: Compilar todos los Apuntes LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'materias/**/*.tex'  # Trigger on any .tex file change under materias

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar latexmk y dependencias de LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Buscar y compilar todos los .tex de materias
        run: |
          find materias -type f -name "*.tex" > texfiles.txt
          while read file; do
            echo "Compilando $file..."
            latexmk -pdf -interaction=nonstopmode "$file"
          done < texfiles.txt

      - name: Mostrar árbol de archivos generado
        run: |
          echo "Contenido del workspace:"
          pwd
          ls -lhR

      - name: Subir todos los PDFs compilados
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: materias/**/*.pdf  # Upload all PDFs under materias
