name: Compilar apuntes LaTeX

on:
  push:
    branches:
      - main
    paths:
      - 'materias/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Compilar todos los archivos .tex en materias/
        uses: xu-cheng/latex-action@v4
        with:
          root_file: |
            $(find materias -type f -name '*.tex')

      - name: Mostrar árbol de archivos generado
        run: |
          echo "Contenido del workspace:"
          pwd
          ls -lhR

      - name: Subir PDFs compilados
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: '**/*.pdf'
