name: Compilar Apuntes LaTeX

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: materias/Calculo_D/primerParcial/primerParcial.tex

      - name: Subur PDF compilado
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: materias/Calculo_D/primerParcial/primerParcial.pdf

