name: Compilar Apuntes LaTeX

on:
  push:
    branches:
     - main
    paths:
      - 'materias/**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Encontrar todos los archivos .tex en el directorio materias
        id: list-tex
        run: |
          TEX_FILES=$(find materias -type f -name '*.tex')
          echo "Archivos encontrados:"
          echo "$TEX_FILES"
          echo "tex_files<<EOF" >> $GITHUB_OUTPUT
          echo "$TEX_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Compilar cada archivo .tex encontrado
        uses: xu-cheng/latex-action@v4
        with:
          root_file: ${{ matrix.tex }}
        strategy:
          matrix:
            tex: ${{ fromJson(steps.list-tex.outputs.tex_files).split('\n') }}

      - name: Mostrar arbol de archivos generado
        run: |
          echo "Contenido del workspace:"
          pwd
          ls -lhR

      - name: Subir PDFs compilados
        uses: actions/upload-artifact@v4
        with:
          name: Apuntes_PDF
          path: '**/*.pdf'
